### ISSUE TITLE
Download links

### ISSUE THREAD

**Issue by ShresthVaibhav** [xenmods/AnimepaheAPI#1]
get download links always throwing errors

`from AnimepaheAPI.animepahe import AnimepaheAPI
animepahe = AnimepaheAPI()
download = animepahe.get_download_links('b97f1565a9ff3325abc70d2194cae3c2fbab476ecc0bba543d587a04b6563455')
print(download)`

error: - 
`Traceback (most recent call last):
  File "C:\Users\luvut\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\luvut\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\luvut\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\luvut\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<module1>", line 3, in <module>
  File "C:\Users\luvut\AppData\Local\Programs\Python\Python310\lib\site-packages\AnimepaheAPI\animepahe.py", line 68, in get_download_links
    resp = resp.json()
  File "C:\Users\luvut\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by xenmods** [comment]
It seems animepahe has updated their backend. I will find some time to work on it and find a fix. I've tested other features and they should work as expected.
